asjard:
  service:
    ## project name
    ## There may be multiple services under a project
    # app: asjard
    ## Current deployment environment, e.g., dev, sit, uat, rc, pro, etc.
    ## If you are connecting to a service_center, you will need to configure development, testing, production, and acceptance here.
    # environment: "dev"
    ## Deployment region, for example: east-1, east-2
    ## Indicates different regions with no intranet connectivity and can only be connected via the public network.
    # region: "default"
    ## Availability Zone, for example: az-1,az-2
    ## Indicates that the devices are within the same region or data center, allowing intranet connectivity.
    # avaliablezone: "default"
    # website: "https://github.com/${asjard.service.app}/${asjard.service.instance.name}"
    # favicon: "favicon.ico"
    ## service description.
    desc: |
      here is the service description, support markdown
    instance:
      ## System unique identification code
      # systemCode: 100
      ## Can be accessed by services in different az
      # shareable: false
      ## Name is the specific deployment or entrypoint name (e.g., "svc-example-api", "svc-example-openapi").
      ## It is used for fine-grained routing and service discovery.
      name: svc-example-api
      ## Group identifies the logical service entity (e.g., "svc-example").
      ## Multiple entrypoints (Names) can share the same Group to indicate they
      ## belong to the same business logic and code base.
      group: svc-example
      ## service version
      # version: 1.0.0
      ## custome service configuration.
      # metadata:
